export const PDF_THEME = {
  page: {
    width: 297,
    height: 210,
    margin: 8,
  },
  panel: {
    width: 65,
  },
  colors: {
    black: '#000000',
    grayDark: '#555555',
    gray: '#888888',
    grayLight: '#dddddd',
    countertopFill: '#f9f8f6',
    countertopStroke: '#000000',
    sinkFill: '#e0f0ff',
    sinkStroke: '#1a5ca8',
    cooktopFill: '#fffdf0',
    cooktopStroke: '#e67700',
    trashFill: '#e8e8e8',
    trashStroke: '#888888',
    wetAreaFill: '#eefcf1',
    wetAreaStroke: '#2f9e44',
    dimLine: '#1a5ca8',
    dimText: '#1a5ca8',
    panelBg: '#ffffff',
    panelHeaderBg: '#1a1a2e',
    panelWarningBg: '#fff8e1',
    panelWarningText: '#7c4e00',
  },
  typography: {
    fontFamily: 'helvetica',
    titleSize: 10,
    sectionSize: 7,
    labelSize: 6,
    valueSize: 8,
    dimSizeMin: 5,
    dimSizeMax: 8,
    componentLabelMin: 5,
    componentLabelMax: 8,
  },
  lineWidths: {
    countertop: 0.6,
    component: 0.3,
    wetArea: 0.3,
    dimension: 0.15,
    border: 0.3,
  }
}
